server:
  port: 8001
#日志输出配置
log:
  level: debug #日志级别
  path: /logs/task/task.log # 最前面加/为绝对路径
#因为继承了base模块，base中有了DataSourceOneConfig.java声明的配置替换了下边的mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.alicyu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept  #eurake通过这个name认定是不是同一个服务
  datasource01:
    mapperPackage: com.alicyu.springcloud.dao.dbone         #mapper包路径
    mapperxmlDir: classpath:mybatis/mapper/dbone/**/*.xml      #mapper.xml路径
    entityPackage: com.alicyu.springcloud.entities.dbone    #实体包路径
    mybatiscfg: classpath:mybatis/mybatis.cfg.xml      #mapper对应mybatis通用配置文件路径
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false
    username: root
    password: zhicheng
    minPoolSize: 3
    maxPoolSize: 25
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    maintenanceInterval: 60
    maxIdleTime: 60
  datasource02:
    mapperPackage: com.alicyu.springcloud.dao.dbtwo         #mapper包路径
    mapperxmlDir: classpath:mybatis/mapper/dbtwo/**/*.xml      #mapper.xml路径
    entityPackage: com.alicyu.springcloud.entities.dbtwo    #实体包路径
    mybatiscfg: classpath:mybatis/mybatis.cfg.xml      #mapper对应mybatis通用配置文件路径
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false
    username: root
    password: zhicheng
    minPoolSize: 3
    maxPoolSize: 25
    maxLifetime: 20000
    borrowConnectionTimeout: 30
    loginTimeout: 30
    maintenanceInterval: 60
    maxIdleTime: 60
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: microservicecloud-dept8001 #同种服务负载均衡需要不同的实例id
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: alicyu-microservicecloud
  company.name: www.alicyu.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT


