server:
  port: 8001
#日志输出配置
log:
  level: debug #日志级别
  path: /logs/task/task.log # 最前面加/为绝对路径
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.alicyu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource01:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false              # 数据库名称
    username: root
    password: zhicheng
    tomcat:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      max-idle: 50                                          # 数据库连接池的最大维持连接数
      initial-size: 5                                       # 初始化连接数
      max-active: 50                                        # 最大活跃数
  datasource02:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false              # 数据库名称
    username: root
    password: zhicheng
    tomcat:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      max-idle: 50                                          # 数据库连接池的最大维持连接数
      initial-size: 5                                       # 初始化连接数
      max-active: 50                                        # 最大活跃数
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: alicyu-microservicecloud
  company.name: www.alicyu.com
  build.artifactId: microservicecloud-provider-dept-8001
  build.version: 0.0.1-SNAPSHOT


